apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-3145-blog
  namespace: default
spec:
  secretName: test-3145-blog-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - test.3145.blog
